### ISSUE TITLE
Add support for cocoa pods

### ISSUE THREAD

**Issue by PoltoraIvana** [auramagi/SwiftWebVTT#1]
Would be great to have support for cocoa pods and/or other package managers

**Comment by auramagi** [comment]
Hi! Carthage is already supported and I plan to add Swift Package Manager support in the future update for Swift 5.1.

I'll look into adding CocoaPods support.

**Comment by PoltoraIvana** [comment]
Sounds great, thank you!

**Comment by auramagi** [comment]
You can now add `pod 'SwiftWebVTT'` to your `Podfile` to use it with CocoaPods,
or add `github "auramagi/SwiftWebVTT"` to your `Cartfile` to use it with Carthage.
